name: rogue
channels:
  - anaconda
  - conda-forge
dependencies:
  - attrs=19.1.0
  - black=19.10
  - boost=1.73.0
  - catch2=2.13.6
  - clang=12.0.0
  - click=7.1.1
  - cmake=3.19.6
  - cytoolz=0.10.1
  - flake8=3.7.9
  - loguru=0.5.3
  - mypy=0.750
#  - panda3d=1.10.9 TODO: re-enable
  - pip
  - progressbar=2.5
  - pudb=2019.2
  - pylint=2.4.4
  - pynput=1.7.1
  - pyrsistent=0.17.3
  - pytest=5.3.0
  - pytest-cov=2.8.1
  - pytest-profiling=1.7.0
  - pytest-sugar=0.9.2
  - pytest-xdist=1.31.0
  - python=3.8
  - pyyaml=5.3.1
  - pip:
      - flake8-bugbear==19.8.0
      - flake8-mypy==17.8.0
      - pygame==2.0.0
      - pygcurse==0.10.2
      - git+https://github.com/arakhmati/ecs
